# Generated by Django 4.2.23 on 2025-07-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField()),
                ('done_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporting New',
                'verbose_name_plural': ' Reporting News',
                'ordering': ('first_name',),
            },
        ),
    ]
