# Generated by Django 4.2.23 on 2025-07-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
